### ISSUE TITLE
bash test.sh Traceback... error

### ISSUE THREAD

**Issue by techhalloman** [ChenyangLEI/deep-video-prior#10]
File "main_IRT.py", line 7, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "main_IRT.py", line 7, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "main_IRT.py", line 7, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'
Traceback (most recent call last):
  File "main_IRT.py", line 7, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

**Comment by ChenyangLEI** [comment]
did you install the environment and activate it？

**Comment by techhalloman** [comment]
yes. working good

**Comment by ChenyangLEI** [comment]
can you show the pip list to me after activate the environment?

**Comment by techhalloman** [comment]
all environment installed good.  activate it.
conda env create -n tensorflow -f environment.yml
conda activate tensorflow

**Comment by ChenyangLEI** [comment]
conda env create -f environment.yml
conda activate deep-video-prior

can you try this?

**Comment by techhalloman** [comment]
just activate this deep-video-prior.. working great. thank you
