### ISSUE TITLE
Final result is flickering 

### ISSUE THREAD

**Issue by delldu** [ChenyangLEI/deep-video-prior#11]
Hi, 
    First all, thank you for your good work !
    We have one question: Final video flickering a little more using you source code. Video source is under your  demo/spatial_white_balance. Attach is test result.
[video.zip](https://github.com/ChenyangLEI/deep-video-prior/files/5709788/video.zip)
    Would you like give us some suggestion ?
    Many thanks.

**Comment by ChenyangLEI** [comment]
hi, can you show the command? Basically, if you use the code in demo.sh, the result should be ok.
