### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by myname1111** [ChenyangLEI/deep-video-prior#13]
When attempting to run main_IRT.py with 6000 frames causes RuntimeError: CUDA out of memory. This could be fixed by reducing batch size or use memory when needed. Also, I`m using google Colab and yes the ram that google collab had offered did not reach the full amount of ram instead, it stopped at 2/3 of it and caused this error

> Traceback (most recent call last):
  File "main_IRT.py", line 139, in <module>
 net_in = torch.from_numpy(net_in).permute(0,3,1,2).float().to(device)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 14.73 GiB total capacity; 12.13 GiB already allocated; 5.88 MiB free; 13.79 GiB reserved in total by PyTorch)

**Comment by ChenyangLEI** [comment]
hi, what is the resolution of your image? Can you run the code successfully using fewer frames?

**Comment by myname1111** [comment]
Yes, I can run the code successfully with 600 instead of 6000. I should also clarify that I'm using the PyTorch version. The resolution of the image 640X480. I'm using the colourization model
