### ISSUE TITLE
Traceback (most recent call last):   File "dvp_video_consistency.py", line 6, in <module>     import scipy.io ModuleNotFoundError: No module named 'scipy'

### ISSUE THREAD

**Issue by SolomGfxcolor** [ChenyangLEI/deep-video-prior#15]
Traceback (most recent call last):
  File "dvp_video_consistency.py", line 6, in <module>
    import scipy.io
ModuleNotFoundError: No module named 'scipy'

**Comment by ChenyangLEI** [comment]
did you install the environment by .xml file?

**Comment by SolomGfxcolor** [comment]
> did you install the environment by .xml file?

Yes 😢 , 
Can you give me colab notebook for this 🙏🏻 please 🙏🏻🌹

**Comment by ChenyangLEI** [comment]
Did you activate the environment?

It is a good idea to implement a colab version. I will  try it when I am available.

**Comment by SolomGfxcolor** [comment]
Ok 👌😁 , am Wait
