### ISSUE TITLE
Wrong resolution of output frames.

### ISSUE THREAD

**Issue by semel1** [ChenyangLEI/deep-video-prior#16]
After running supplied demo (regardless of used task ) resolution of output video frames is different from than resolution of input/processed frames. e.g. resolution of "goat_input and goat_processed" frames is 854x480 however output result is 832x480.
Processing my own frames (regardless of used task) with 1440x1080 delivers frames with 1440x1056.

**Comment by ChenyangLEI** [comment]
Yes. We crop the image so that the images can be divided by 32.

**Comment by semel1** [comment]
Thank you.
