### ISSUE TITLE
The url of downloading VGG.zip is invalid now

### ISSUE THREAD

**Issue by Ssakura-go** [ChenyangLEI/deep-video-prior#18]
Dear author, I tried to implement the code for learning, however, an error appeared when I compiled the command [ python download_VGG.py ], which points to that the url of downloading VGG.zip is invalid now.
Therefore, if convenient, could you please show me another one?

**Comment by ChenyangLEI** [comment]
Can you try this?

https://drive.google.com/file/d/1Hm_VS5Acxge3t0TUhKFZa8c0QFw2TTr_/view?usp=sharing
