### ISSUE TITLE
The code to calculate Ewarp

### ISSUE THREAD

**Issue by wdrink** [ChenyangLEI/deep-video-prior#4]
Hi, thanks a lot for your amazing work. I wonder whether you could share your code to calculate Ewarp, which is mentioned in your paper to evaluate temporal consistency. Thanks a lot.

**Comment by yzxing87** [comment]
Hi, to calculate Ewarp, you need to install PWC-Net (https://github.com/NVlabs/PWC-Net/blob/master/PyTorch/README.md) by yourself. Here we provide some main functions for Ewarp. You can use these functions to evaluate temporal inconsistency once you successfully installed PWC-Net. 
[Ewarp.zip](https://github.com/ChenyangLEI/deep-video-prior/files/5567021/Ewarp.zip)

**Comment by wdrink** [comment]
Ok, thanks a lot.
