### ISSUE TITLE
待处理数据文件比较多，CPU占用爆表，电脑卡死了

### ISSUE THREAD

**Issue by stone100010** [ChenyangLEI/deep-video-prior#5]
我做了一个戴口罩的视频修改功能，videoFrames文件夹下是视频拆帧数据，processed/colorization文件夹下是戴面具处理的数据，两文件夹各6000张图片(1920*720)，使用的是：
python main_IRT.py --max_epoch 1 --input videoFrames --processed processed/colorization --model colorization --with_IRT 1 --IRT_initialization 1 --output ./result/colorization/AddMask 
我的CPU直接干到100%， 内存128也不够用，电脑就卡住了，具体配置如下：
"--use_gpu", default=1,
tensorflow-gpu=1.13.1

期待您的解答，感谢您！

**Comment by ChenyangLEI** [comment]
1. 首先搜索“data_in_memory”这个变量，把所有关于这个遍历的代码注释掉
2. 其次，在使用到“data_in_memory”这个变量的代码用第133行的代码替代掉（用于提供“net_in”和“net_gt”变量）

**Comment by splinter21** [comment]
卡死了是因为内存爆炸不停往swap里面写入虚拟内存打满CPU导致其他进程没得CPU用吧
