### ISSUE TITLE
在老视频上色的处理中，颜色不准确受到之前帧图片颜色影响

### ISSUE THREAD

**Issue by stone100010** [ChenyangLEI/deep-video-prior#6]
-------------
上面是计算出来的图片，具体命令如下：
python main_IRT.py --max_epoch 50 --input demo/colorization/ai_input1000 --processed demo/colorization/ai_processed1000 --model enhancement --with_IRT 1 --IRT_initialization 1 --output ./result/colorization1000/
表现效果为：第三张图片偏黄，且受到了之前帧炮弹爆炸画面黄光的影响。
--------------
同样的model colorization参数也试过，表现效果为：图片直接变成了晚上，深蓝色的天空，与实际上色图片差距太大。
--------------
小弟才学有限，对大佬十分敬仰，期待您的解答。

**Comment by ChenyangLEI** [comment]
hi 请问你train了多少个epochs

**Comment by stone100010** [comment]
50个，超了？

**Comment by ChenyangLEI** [comment]
可能你用的frames数量比较不一样，理论上最终都回overfit到你的原始处理效果。你可以提高max_epoch的数量，直到非常接近你的预处理视频。

**Comment by stone100010** [comment]
视频拆帧1000张图片，1920*720，但是有多个镜头切换，爬雪山过草地运炸弹都有，我是把他们分镜头处理还是直接max_epoch调到一两百？

**Comment by ChenyangLEI** [comment]
我们测试时候是分镜头处理的，所以我也建议你分镜头处理。

**Comment by stone100010** [comment]
好的，感谢！
